# inventory/hosts.yml
all:
  hosts:
    ubuntu-s-1vcpu-1gb-fra1-01:
      ansible_host: 159.89.106.125 # Replace with your target host's IP/hostname
      ansible_user: root # Replace with your SSH username

    simo-Precision-T3610:
      ansible_host: localhost # Replace with your target host's IP/hostname
      ansible_user: root # Replace with your SSH username
  vars:
    ansible_python_interpreter: /usr/bin/python3 # Explicitly set the Python 3 interpreter
    app_dir: /opt/tornado-tutorial
    venv_dir: "{{ app_dir }}/venv"
    app_user: www-data # Dedicated user for the application

